spring:
  datasource:
    url: jdbc:mysql://project-db-campus.smhrd.com:3307/campus_24K_LI2_p2_2
    username: campus_24K_LI2_p2_2
    password: smhrd2
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8083
  address: 0.0.0.0

file:
  upload-dir: uploads/


